### ISSUE TITLE
[Sample Onboard Request] Large Scale Notification Bot

### ISSUE THREAD

**Issue by yiqing-zhao** [OfficeDev/TeamsFx-Samples#1040]
**Owner:**
@yiqing-zhao 

**ID:**
large-scale-notification

**Title:**
Large Scale Notification Bot

**Description:**
This sample demonstrates the architecture of a Teams notfication bot app created by Teams Toolkit to send individual chat messages to a large number of users in a tenant.

**Onboard Date:**
ASAP

**Tags:**
You can give your samples a set of tags so that users can easily locate your sample from a group of samples. Those tags can be:
- TS
- Bot
- Azure Durable Functions
- Notification
- Large user scale
You can customize the tag you used for your sample, the recommended number of tags is less than 5.

**Time:**
30 mins to run

**Configuration:**
Manual configurations required

**Thumbnail:**
https://github.com/OfficeDev/TeamsFx-Samples/blob/yiqingzhao/largescale-notification/large-scale-notification/assets/thumbnail.png

**(Optional) Demo GIF:**
No GIF

**(Source code in this Repo) Source Code PR:**
https://github.com/OfficeDev/TeamsFx-Samples/pull/1014

**(Source code NOT in this Repo) Sample URL:**
The URL if your sample code resides in another sample repo. It's better to use a tag instead of a branch for stablility.
E.g., "https://github.com/xxx/xxx/tree/v1.0/xxx".

**(Optional) Minimum Teams Toolkit Version:**
V5

**(Optional) Maximum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - maximum version

**Comment by tecton** [comment]
PR is verified.

**Comment by summzhan** [comment]
The sample passed PM review and passed test.

**Comment by summzhan** [comment]
next step: Add to sample gallery.

**Comment by tecton** [comment]
Onboarding PR: #1054
