### ISSUE TITLE
[Sample Onboard Request] Graph Connector Bot

### ISSUE THREAD

**Issue by formulahendry** [OfficeDev/TeamsFx-Samples#1060]
**Owner:**
@formulahendry 

**ID:**
graph-connector-bot

**Title:**
Graph Connector Bot

**Description:**
This sample app showcases how to build a Teams command bot that queries custom data ingested into Microsoft Graph using Graph connector.

**Tags:**
- TS
- Bot
- Microsoft Graph connectors

**Time:**
30mins to run

**Configuration:**
Manual configurations required

**Thumbnail:**
https://github.com/OfficeDev/TeamsFx-Samples/blob/dev/graph-connector-bot/assets/thumbnail.png

**(Optional) Demo GIF:**
https://github.com/OfficeDev/TeamsFx-Samples/blob/dev/graph-connector-bot/assets/sampleDemo.gif

**(Source code in this Repo) Source Code PR:**
https://github.com/OfficeDev/TeamsFx-Samples/pull/469

**(Source code NOT in this Repo) Sample URL:**
N/A

**(Optional) Minimum Teams Toolkit Version:**
V5

**(Optional) Maximum Teams Toolkit Version:**
N/A

**Comment by formulahendry** [comment]
Add @MuyangAmigo for awareness.

**Comment by formulahendry** [comment]
@tecton Please update config to onboard this sample.

**Comment by tecton** [comment]
Onboarding PR: #1075

**Comment by tecton** [comment]
@formulahendry I've onboarded sample to TTK sample gallery. It will be available in next release version, and you can also check it in TTK daily build versions.

**Comment by summzhan** [comment]
checked already in Gallery, hence close the tricket.
