### ISSUE TITLE
[Sample Onboard Request] Teams Messaging Extensions Search

### ISSUE THREAD

**Issue by frankqianms** [OfficeDev/TeamsFx-Samples#1077]
**Owner:**
@frankqianms 

**ID:**
msgext-search-python

**Title:**
Teams Messaging Extensions Search using Python

**Description:**
There are two basic types of Messaging Extension in Teams: [Search-based](https://docs.microsoft.com/microsoftteams/platform/messaging-extensions/how-to/search-commands/define-search-command) and [Action-based](https://docs.microsoft.com/microsoftteams/platform/messaging-extensions/how-to/action-commands/define-action-command). This sample illustrates how to build a Search-based Messaging Extension.

**Tags:**
You can give your samples a set of tags so that users can easily locate your sample from a group of samples. Those tags can be:
- Python
- Message Extension
- Bot Framework
- Local debug
You can customize the tag you used for your sample, the recommended number of tags is less than 5.

**Time:**
5mins to run

**Configuration:**
Manual configurations required.
Users need to manage virtual environments and pip install dependencies before local debug.
This python message extension sample only supports local debug currently.

**(Source code NOT in this Repo) Sample URL:**
[Teams Messaging Extensions Search](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search/python#teams-messaging-extensions-search)

**Thumbnail**
./Images/9-mention-Search-Result.png
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msgext-search/python/Images/9-mention-Search-Result.png

**Demo GIF**
./Images/msgext-search.gif
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msgext-search/python/Images/msgext-search.gif

**Comment by MuyangAmigo** [comment]
Can we update the title to indicate it's using Python: Teams Message Extension Search using Python

**Comment by HuihuiWu-Microsoft** [comment]
For source code:
1. please help run validation tool (https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/validation-tool) against this sample
2. Better use latest manifest version TTK supported, i.e. 1.16 in Teams manifest file
3. Better update .env.local and teamsapp.local.yml to include APP_NAME_SUFFIX variable to align with latest change
4. There's an additional [sample.json](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msgext-search/python/sample.json) file which is conflict with [assets/sample.json](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msgext-search/python/assets/sample.json)

**Comment by frankqianms** [comment]
Finished running validation tool, and got the result.
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/109947924/cf17e8e6-e7d4-4484-aee8-34c6a0bbb32c)
There are several failed validations. 
1. Since it is a python sample, there is no package.json.
2. Since it is an external sample and the Microsoft-Teams-Samples team insists to use `appManifest/` rather than `appPackage/` for there considerations, there are three failed validations on that.
3. Since this sample only supports local debug now, there is no env/.env.dev now.

**Comment by frankqianms** [comment]
> For source code:
> 
> 1. please help run validation tool (https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/validation-tool) against this sample
> 2. Better use latest manifest version TTK supported, i.e. 1.16 in Teams manifest file
> 3. Better update .env.local and teamsapp.local.yml to include APP_NAME_SUFFIX variable to align with latest change
> 4. There's an additional [sample.json](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msgext-search/python/sample.json) file which is conflict with [assets/sample.json](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msgext-search/python/assets/sample.json)

For conflict sample.json files, sample owner @Mohammed-MSFT has awared this problem and would updated the repo soon.

**Comment by summzhan** [comment]
onboarded in gallery, close the ticket
