### ISSUE TITLE
[Sample Onboard Request] Ingest custom API data into Microsoft 365 with a Microsoft Graph connector

### ISSUE THREAD

**Issue by garrytrinder** [OfficeDev/TeamsFx-Samples#1083]
**Owner:**
@waldekmastykarz @garrytrinder

**ID:**
gc-nodejs-typescript-food-catalog

**Title:**
Ingest custom API data into Microsoft 365 with a Microsoft Graph connector

**Description:**
This sample project uses Teams Toolkit for Visual Studio Code to simplify the process of creating a Microsoft Graph connector that ingests data from a custom API to Microsoft Graph. It provides an end to end example of creating the connector, ingesting content and refreshing the ingested content on a schedule. It also includes the simplified admin experience which means that admins can toggle the connector on and off from the Microsoft Teams admin center.

**Tags:**

- TS
- Graph connector
- Azure Function
 
**Time:**
5mins to run

**Configuration:**
[Post F5 tasks](https://github.com/pnp/graph-connectors-samples/tree/main/samples/nodejs-typescript-food-catalog#2-enable-graph-connector)

**Thumbnail:**
https://github.com/pnp/graph-connectors-samples/tree/main/samples/nodejs-typescript-food-catalog/assets/ttk_thumb.png

**Demo GIF:**
https://github.com/pnp/graph-connectors-samples/tree/main/samples/nodejs-typescript-food-catalog/assets/ttk.gif

**Sample URL:**
https://github.com/pnp/graph-connectors-samples/tree/main/samples/nodejs-typescript-food-catalog

**Comment by garrytrinder** [comment]
FYI @MuyangAmigo @pierceboggan assets (thumbnail and GIF) are awaiting the merge of https://github.com/pnp/graph-connectors-samples/pull/30

**Comment by MuyangAmigo** [comment]
Awesome @garrytrinder ! We will get this merged by next Monday. @tecton

**Comment by tecton** [comment]
@MuyangAmigo @garrytrinder I've created a test ticket to verify the README of the sample. We'll update the progress in this issue.

**Comment by summzhan** [comment]
Thanks @garrytrinder , the README file looks good to me, @tecton will help you merge and config this sample.

**Comment by garrytrinder** [comment]
Thanks for the comments @hellyzh apologies for the inconvenience.

1. `azure-functions-core-tools` is in the `package.json` as a dev dependency so should be available on first run as the very first task is `npm install`. Did you have the core tools package installed globally before running the sample?
1. We think that this is a regression in the API as we are sending a result type template to Graph in the API call to create the connection, but we noticed that recently the result type was not being created. For context, the API call to create a connection is on the beta endpoint so is suspect to changes without warning. We will update the instructions to handle the new behaviour seen.
1. This is related to above, with no result type template being created, search uses a default template.
1. Yes this is correct. The app created by the sample is uploaded to the Teams Organisational App Store during F5, this is a requirement for the connector, therefore we don't side load the app for the developer.

**Comment by tecton** [comment]
Hi @garrytrinder, I've confirmed with @hellyzh that he can successfully run "F5" after installing "Azure Functions" extension. So, I would suggest adding it as a prerequisite. For point 2 and 3, please update the instructions in README or codes.

I'll continue the onboarding process.

**Comment by garrytrinder** [comment]
> Hi @garrytrinder, I've confirmed with @hellyzh that he can successfully run "F5" after installing "Azure Functions" extension. So, I would suggest adding it as a prerequisite. For point 2 and 3, please update the instructions in README or codes.
> 
> I'll continue the onboarding process.

Thanks for the update, good to know that there is a dependency on the extension. We have it listed in the `extensions.json` file, but will add to the pre-reqs.

**Comment by tecton** [comment]
@garrytrinder @MuyangAmigo @summzhan this sample has been added to the sample gallery of Teams Toolkit prerelease version.

**Comment by garrytrinder** [comment]
Great news! Thank you for the update @tecton 👍

**Comment by summzhan** [comment]
the sample onboarded successfully to TTK prerelease version, close the ticket.
