### ISSUE TITLE
[Sample Onboard Request] Reddit Link Unfurling sample

### ISSUE THREAD

**Issue by yukun-dong** [OfficeDev/TeamsFx-Samples#1101]
**Owner:**
@yukun-dong 
**ID:**
reddit-link-unfurling

**Title:**
Format Reddit Link into Adaptive Card

**Description:**
This sample application showcases how to build a Teams application (Link Unfurling, a type of Message Extension) that can format the Reddit link into an Adaptive Card when a user pastes a Reddit link into the compose message area.

**Tags:**
JS, Message Extension, Link Unfurling

**Time:**
10 mins to run

**Configuration:**
Manual configurations required

**Thumbnail:**
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/msgext-link-unfurling-reddit/nodejs/doc/image/link.png

**(Source code in this Repo) Source Code PR:**
The link to pull request that contains sample source codes.

**(Source code NOT in this Repo) Sample URL:**
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-link-unfurling-reddit/nodejs

**Comment by yukun-dong** [comment]
> @yukun-dong Can we update the following:
> 
> 1. Title: `Format Reddit Link into Adaptive Card`
> 2. Description: `This sample application showcases how to build a Teams application (Link Unfurling, a type of Message Extension) that can format the Reddit link into an Adaptive Card when a user pastes a Reddit link into the compose message area.`

Sure, let me update.

**Comment by tecton** [comment]
Hi @yukun-dong @MuyangAmigo, the sample has been onboarded. You could find it in daily release TTK sample gallery.
