### ISSUE TITLE
Add app icon to samples

### ISSUE THREAD

**Issue by erikadoyle** [OfficeDev/TeamsFx-Samples#1102]
Logging this ask from M365 product teams--would it be possible to update TeamsFx samples with an app icon? We use a number of them in walkthrough tutorials in the docs, and got feedback from PMs that the generic app icon in our screenshots doesn't look realistic/professional. 

Thanks for your consideration~

**Comment by MuyangAmigo** [comment]
@erikadoyle Great suggestion! Is there a suggested asset we could use or do you expect us to create a custom app icon?

**Comment by erikadoyle** [comment]
I don't know of any, but as a suggestion @girliemac and I were thinking maybe simply using the existing Fluent "apps" icon, but applying purple/blue from M365 logo to it: 

![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/2170770/c336808a-791c-45ec-bafb-d39928a1642b) + ![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/2170770/a87a47c2-590d-47c4-9468-0fa0e06a412f)

. . . what do you think? Is there someone from design that could help?
