### ISSUE TITLE
Error Building React Retail Dasboard

### ISSUE THREAD

**Issue by GeorgiaGit** [OfficeDev/TeamsFx-Samples#1111]
Visual Studio Code Teams Toolkit extension, Samples, Contoso Retail Dashboard.

Dev environment
+-- @microsoft/generator-sharepoint@1.17.4
+-- corepack@0.10.0
+-- gulp-cli@2.3.0
`-- npm@8.5.0n

node version 16.14.2

On Run and Debug using the Teams Workbench, the server fails: 
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/71793225/49e754d3-8cbf-4db9-92c6-8b31c39f5200)

Any idea how to fix this?

I tried running npm i @fluentui/react without success.

**Comment by yuqizhou77** [comment]
Hi @GeorgiaGit Could you try to replace ‘~’ with the relative path to "node_modules" in the "src" folder and try if it can work?
