### ISSUE TITLE
[Sample Onboard Request] Intelligent Data Chart Generator

### ISSUE THREAD

**Issue by huimiu** [OfficeDev/TeamsFx-Samples#1125]
**Owner:**
@huimiu 

**ID:**
intelligent-data-chart-generator

**Title:**
Intelligent Data Chart Generator

**Description:**
This intelligent Microsoft Teams Tab app is powered by Azure OpenAI, which helps users generating data charts based on users' description of the data chart in human language. There is an input box where users tell the Tab app what data chart they want to generate, and the app interprets user's requirements then generate visual charts. The data is from Azure SQL. This sample demonstrates how to build a seamless and intuitive experience for accessing and interpreting data.

**Tags:**
- TS
- Tab
- Azure Functions

**Time:**
30mins to run

**Configuration:**
Manual configurations required.

**Thumbnail:**
https://github.com/OfficeDev/TeamsFx-Samples/blob/dev/intelligent-data-chart-generator/assets/thumbnail.png

**(Optional) Demo GIF:**
https://github.com/OfficeDev/TeamsFx-Samples/blob/dev/intelligent-data-chart-generator/assets/sampleDemo.gif

**(Source code in this Repo) Source Code PR:**
https://github.com/OfficeDev/TeamsFx-Samples/pull/1124

**(Source code NOT in this Repo) Sample URL:**
N/A

**(Optional) Minimum Teams Toolkit Version:**
V5

**(Optional) Maximum Teams Toolkit Version:**
N/A

**Comment by summzhan** [comment]
Reviewed the README file and left comments, please resolve. 

Also please update the description in this ticket.

**Comment by tecton** [comment]
Onboard PR: https://github.com/OfficeDev/TeamsFx-Samples/pull/1140

**Comment by tecton** [comment]
@huimiu @summzhan This sample has been onboarded to `dev` branch. You should be able to see it in daily build version TTK.

**Comment by summzhan** [comment]
@tecton , @huimiu The sample already on stable version v5.6.0. Close this ticket.
