### ISSUE TITLE
[Sample Onboard Request] Containerized Bot App with SSO Enabled

### ISSUE THREAD

**Issue by hund030** [OfficeDev/TeamsFx-Samples#1126]
**Owner:**
@hund030 

**ID:**
bot-sso-docker

**Title:**
Containerized Bot App with SSO Enabled

**Description:**
This is an containerized Microsoft Teams Bot app demonstrating how to integrate with Bot Framework SDK, TeamsFx SDK, and Graph SDK to implement SSO (Single Sign-On) feature that retrieves profile photos for currently signed-in users.

**Tags:**
- TS
- Bot
- Docker
- Single Sign On

**Time:**
5 mins to run

**Configuration:**
Ready for local debug

**Thumbnail:**
https://github.com/OfficeDev/TeamsFx-Samples/blob/sso-bot-docker/bot-sso-docker/assets/thumbnail.png

**(Optional) Demo GIF:**
https://github.com/OfficeDev/TeamsFx-Samples/blob/sso-bot-docker/bot-sso-docker/assets/sampleDemo.gif

**(Source code in this Repo) Source Code PR:**
https://github.com/OfficeDev/TeamsFx-Samples/pull/1122

**(Optional) Minimum Teams Toolkit Version:**
V5.0.0

**(Optional) Maximum Teams Toolkit Version:**
N/A

**Comment by tecton** [comment]
Onboarding PR: https://github.com/OfficeDev/TeamsFx-Samples/pull/1156

**Comment by tecton** [comment]
@summzhan @hund030 This sample has been onboarded. You could view it in daily build version now.

**Comment by summzhan** [comment]
@tecton , @hund030 , the sample is released on stable version, close this ticket for now.
