### ISSUE TITLE
[Sample Onboard Request] Teams Chef Bot

### ISSUE THREAD

**Issue by MuyangAmigo** [OfficeDev/TeamsFx-Samples#1164]
**Owner:**
Corina Gum <corinagum@microsoft.com>
GH Account: https://github.com/corinagum

**ID:**
teams-chef-bot

**Title:**
Teams Chef Bot

**Description:**
This is a conversational bot for Microsoft Teams that impersonates a Chef to help you cook Teams apps.

**Tags:**
You can give your samples a set of tags so that users can easily locate your sample from a group of samples. Those tags can be:
- TS
- Bot
- Teams AI Library

**Time:**
5mins to run

**Configuration:**
Ready for local debug

**Thumbnail:**
assets/TeamsChef002.jpg

**(Source code NOT in this Repo) Sample URL:**
https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai.a.teamsChefBot

**Comment by tecton** [comment]
PR: #1165 

@MuyangAmigo The image is not compatible with current TTK because it uses [GIT LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files). Could you please help to upload a new screenshot with new Teams UI?

**Comment by tecton** [comment]
@MuyangAmigo The sample has been onboarded. You could check it in latest daily build.
