### ISSUE TITLE
The graph-connector-app does not work

### ISSUE THREAD

**Issue by Krizz1983** [OfficeDev/TeamsFx-Samples#1209]
When running the graph-connector-app example I get the error:
------------------------------------------------------------------------------------------------------------
[Mon, 18 Mar 2024 01:45:25 GMT] : @microsoft/teamsfx : Verbose - Failed to call acquireTokenSilent. Reason: uninitialized_public_client_application: You must call and await the initialize function before attempting to call any other MSAL API.  For more visit: aka.ms/msaljs/browser-errors. 
useTeamsUserCredential.js:22 [Mon, 18 Mar 2024 01:45:25 GMT] : @microsoft/teamsfx : Verbose - Failed to call ssoSilent. Reason: uninitialized_public_client_application: You must call and await the initialize function before attempting to call any other MSAL API.  For more visit: aka.ms/msaljs/browser-errors. 
useTeamsUserCredential.js:22 [Mon, 18 Mar 2024 01:45:25 GMT] : @microsoft/teamsfx : Error - Failed to get access token cache silently, please login first: you need login first before get access token.
------------------------------------------------------------------------------------------------------------

If I install a new teams sample and follow these instructions:
https://learn.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab
I get the same error.

Also tried with code that previously worked (and still work in old repos) and get the same error.

Not sure if this is the right place to post the error - seems like a bug with the @microsoft/teamsfx-react.

**Comment by formulahendry** [comment]
@Krizz1983  Could you please try updating "@microsoft/teamsfx" and "@microsoft/teamsfx-react" to below version?
https://github.com/OfficeDev/TeamsFx-Samples/blob/7de1573f3fb92bde0a8067cf46239d07b7e97618/graph-connector-app/tabs/package.json#L14-L15

There is some change in MSAL lib, so quick workaround is to downgrade sdk version.

**Comment by Krizz1983** [comment]
Thanks a lot @formulahendry for the solution 👍🏻😀🚀
