### ISSUE TITLE
[Sample Onboard Request] Word-Add-In-Writing-Assistant

### ISSUE THREAD

**Issue by xiruatms** [OfficeDev/TeamsFx-Samples#1214]
**Owner:**
xiruatms

**ID:**
Word-Add-In-Writing-Assistant

**Title:**
Word-Add-In-Writing-Assistant

**Description:**
This add-in demonstrates Word add-in capabilities to help users check errors, improve writing, and rephrase content.

**Tags:**
"JS", "React"

**Time:**
5mins to run.

**Configuration:**
"Ready for local debug" .

**Thumbnail:**
https://github.com/OfficeDev/Office-Samples/blob/main/Word-Add-in-WritingAssistant/assets/thumbnail.png

**(Optional) Demo GIF:**
https://github.com/OfficeDev/Office-Samples/blob/main/Word-Add-in-WritingAssistant/assets/sampleDemo.gif

**(Source code in this Repo) Source Code PR:**
Code in another Repo

**(Source code NOT in this Repo) Sample URL:**
https://github.com/OfficeDev/Office-Samples/blob/main/Word-Add-in-WritingAssistant

**(Optional) Minimum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - minimum version

**(Optional) Maximum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - maximum version

**Comment by summzhan** [comment]
Suggest the following update to this sample README file:
1. Give a title to this README file.
2. Do not use name :"M365 Toolkit". Remove keyword: M365. Just use "Teams Toolkit"
3.  The command name keep consistent with screenshot (or update your screenshot): 
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/113089977/f0d64cd2-6d10-4063-88c1-f60cd336901f)

**Comment by hermanwenhe** [comment]
updated
