### ISSUE TITLE
[Sample Onboard Request] Excel-Add-in-Custom-Function-Using-WebWorker

### ISSUE THREAD

**Issue by XuanZhouMSFT** [OfficeDev/TeamsFx-Samples#1218]
**Owner:**
penglongzhaochina

**ID:**
Excel-Add-in-Custom-Function-Using-WebWorker

**Title:**
Custom Function Sample Using Web Worker

**Description:**
Shows how to use web workers in custom functions to prevent blocking the UI of your Office Add-in.

**Tags:**
"Custom Function",  "JS", "Excel", "WebWorker", "Office Add-in"

**Time:**
5mins to run

**Configuration:**
Ready for local debug

**Thumbnail:**
https://github.com/OfficeDev/Office-Samples/blob/main/Excel-Add-in-Custom-Function-Using-WebWorker/assets/taskpane.png

**(Optional) Demo GIF:**
https://github.com/OfficeDev/Office-Samples/blob/main/Excel-Add-in-Custom-Function-Using-WebWorker/assets/sampleDemo.gif

**(Source code in this Repo) Source Code PR:**
In another repo

**(Source code NOT in this Repo) Sample URL:**
https://github.com/OfficeDev/Office-Samples/blob/main/Excel-Add-in-Custom-Function-Using-WebWorker/

**(Optional) Minimum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - minimum version

**(Optional) Maximum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - maximum version

**Comment by summzhan** [comment]
Suggest the following update to this sample README file:
1. Give a title to this README file.
2. Do not use name :"M365 Toolkit". Remove keyword: M365. Just use "Teams Toolkit"
3.  The command name keep consistent with screenshot (or update your screenshot): 
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/113089977/f0d64cd2-6d10-4063-88c1-f60cd336901f)

**Comment by hermanwenhe** [comment]
updated

**Comment by XuanZhouMSFT** [comment]
[like]  Xuan Zhou reacted to your message:
________________________________

**Comment by yuqizhou77** [comment]
Need to update readme about additional extension to install.
