### ISSUE TITLE
[Sample Onboard Request] Word-Add-In-AIGC

### ISSUE THREAD

**Issue by xiruatms** [OfficeDev/TeamsFx-Samples#1224]
**Owner:**
xiruatms

**ID:**
Word-Add-In-AIGC

**Title:**
Word-Add-In-AIGC

**Description:**
This sample shows a practical Word Add-in with content insertion features, utilizing either AI or predefined content.

**Tags:**
"TS", "React"

**Time:**
"5mins to run".

**Configuration:**
"Ready for local debug".

**Thumbnail:**
https://github.com/OfficeDev/Office-Samples/blob/main/Word-Add-in-AIGC/assets/thumbnail.png

**(Optional) Demo GIF:**
https://github.com/OfficeDev/Office-Samples/blob/main/Word-Add-in-AIGC/assets/sampleDemo.gif

**(Source code in this Repo) Source Code PR:**
Code in another Repo

**(Source code NOT in this Repo) Sample URL:**
https://github.com/OfficeDev/Office-Samples/blob/main/Word-Add-in-AIGC

**(Optional) Minimum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - minimum version

**(Optional) Maximum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - maximum version

**Comment by summzhan** [comment]
Suggest the following update to this sample README file:
1. Give a title to this README file.
2. Do not use name :"M365 toolkit"
3.  The command name keep consistent with screenshot: 
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/113089977/f0d64cd2-6d10-4063-88c1-f60cd336901f)

**Comment by hermanwenhe** [comment]
updated

**Comment by summzhan** [comment]
> updated

@hermanwenhe , the README file still missing a title.
