### ISSUE TITLE
how to require apiEndpoint?

### ISSUE THREAD

**Issue by hanluxq** [OfficeDev/TeamsFx-Samples#357]
i want to require apiEndpoint by teamsfx.getConfig("apiEndpoint"),
but it doesn't work, should i config any files?

**Comment by tecton** [comment]
Hi @hanluxq, could you provide more information like reproduce steps about the issue?
`teamsfx.getConfig("apiEndpoint")` is the designed way to get the variable and it will return value if you have added `Azure Function` to your teamsfx project.

**Comment by hanluxq** [comment]
never mind! thanks for your reply, i have resolved this problem&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ning ***@***.***&gt;; 
发送时间: 2022年5月7日(星期六) 上午9:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OfficeDev/TeamsFx-Samples] how to require apiEndpoint? (Issue #357)





 
Hi @hanluxq, could you provide more information like reproduce steps about the issue?
 teamsfx.getConfig("apiEndpoint") is the designed way to get the variable and it will return value if you have added Azure Function to your teamsfx project.
