### ISSUE TITLE
Can not aquire token in sample 'graph-connector-app'

### ISSUE THREAD

**Issue by hsteweri** [OfficeDev/TeamsFx-Samples#362]
I am trying to run the sample "graph-connector-app". 
When I hit F5 and the app opens it is trying to execute the following code in tabs\src\components\sample\lib\useLogin.ts :
`await teamsfx.getCredential().getToken(scopes);`
This outputs the following console messages but then hangs with an never ending loading-circle and the function never finishes. The tab never displays anything.
`[Tue, 03 May 2022 12:44:02 GMT] : @microsoft/teamsfx : Info - Create teams user credential
tabs/src/components/sample/lib/useTeamsFx.ts:14`
`[Tue, 03 May 2022 12:44:02 GMT] : @microsoft/teamsfx : Verbose - Validate authentication configuration
tabs/src/components/sample/lib/useTeamsFx.ts:14`
`[Tue, 03 May 2022 12:44:02 GMT] : @microsoft/teamsfx : Info - Create teams user credential
tabs/src/components/sample/lib/useTeamsFx.ts:14`
`[Tue, 03 May 2022 12:44:02 GMT] : @microsoft/teamsfx : Verbose - Validate authentication configuration
tabs/src/components/sample/lib/useTeamsFx.ts:14`
`[Tue, 03 May 2022 12:44:02 GMT] : @microsoft/teamsfx : Info - Get basic user info from SSO token`

**Comment by adashen** [comment]
related bug in https://github.com/OfficeDev/TeamsFx/issues/4907 will track in teamsfx repo

**Comment by adashen** [comment]
related bug closed so close here.
