### ISSUE TITLE
hello-world-in-meeting - Missing RSC permissions to enable Meeting Stage Share button

### ISSUE THREAD

**Issue by Benjiiim** [OfficeDev/TeamsFx-Samples#504]
It seems that the hello-world-in-meeting is missing the now required RSC permissions to enable Meeting Stage Share button.

According to https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#resource-specific-delegated-permissions, the following permissions in manifest should solve the issue:

"authorization": {
 "permissions": {
 "orgWide": [],
 "resourceSpecific": [
 {
 "name": "MeetingStage.Write.Chat",
 "type": "Delegated"
 },
 {
 "name": "ChannelMeetingStage.Write.Group",
 "type": "Delegated"
 }
 ]
 }
 }
}

**Comment by JerryYangKai** [comment]
Hi @Benjiiim, thanks for your contribute.
Now his sample aims to provide the simplest in-meeting app, so many features is not enabled.
We are going to provide another in-meeting samples for more complicated scenario.

**Comment by JerryYangKai** [comment]
@Benjiiim Sure, I will tag this as a Bug and resolved it in next release.
Thanks!

**Comment by JerryYangKai** [comment]
Fixed in PR https://github.com/OfficeDev/TeamsFx-Samples/pull/506
