### ISSUE TITLE
SSOCommand race condition issue

### ISSUE THREAD

**Issue by ValeriyMaslenikov** [OfficeDev/TeamsFx-Samples#576]
Hey there.

I've found that the template implementation of `bot-sso` has issues with race conditions if multiple users do the authentication at the same time. Especially the case may be when we invite the user to do authorization when the bot is installed, but the user does that in a couple of minutes and someone at this time will already do the authorization.

### Change the code:

To `bot/commands/index.ts` add two commands which will be inherited from the SSOCommand:
``` diff
import { BotCommand } from "../helpers/botCommand";
import { LearnCommand } from "./learn";
+ import { ShowUserPrincipalName } from "./showUserPrincipalName";
+ import { ShowUserDisplayName } from "./showUserDisplayName";
import { WelcomeCommand } from "./welcome";

export const commands: BotCommand[] = [
  new LearnCommand(),
+ new ShowUserPrincipalName(),
+ new ShowUserDisplayName(),
  new WelcomeCommand(),
];
```

Make these commands to make some distinguishable texts.
`./showUserPrincipalName`:
```typescript
import { TurnContext } from "botbuilder";
import { SSOCommand } from "../helpers/botCommand";

export class ShowUserPrincipalName extends SSOCommand {
  constructor() {
    super();
    this.matchPatterns = [/^\s*show_principal\s*/];
    this.operationWithSSOToken = this.showUserInfo;
  }

  async showUserInfo(context: TurnContext, ssoToken: string) {
    await context.sendActivity("I will show you the user principal name");
  }
}
```

`./showUserDisplayName.ts`:
```typescript
import { TurnContext } from "botbuilder";
import { SSOCommand } from "../helpers/botCommand";

export class ShowUserDisplayName extends SSOCommand {
  constructor() {
    super();
    this.matchPatterns = [/^\s*show_display\s*/];
    this.operationWithSSOToken = this.showUserInfo;
  }

  async showUserInfo(context: TurnContext, ssoToken: string) {
    await context.sendActivity("I will show you the user display name");
  }
}
```

### User scenario

- Open two teams instances for different users (A and B) in different browsers and install the bot for both of these users
- In the A – run the command `show_principal`
- in the B – run the command `show_display`
- in the A – do the authorization flow  
- in the B – do the authorization flow

**Expected result:** for user A the sent text: `I will show you the user principal name`, for the user B the bot sent text: `I will show you the user display name`.
**Actual result:** for user A the bot sent text `I will show you the user display name`, for user B the bot didn't send any text.

Next steps to make sure that code is right and it's the race condition issue, run:
- in the A – `show_principal` and it will return `I will show you the user principal name`.
- in the B – `show_display` and it will return `I will show you the user display name`.

## The reason of the problem

When the `botCommand` is `run` it sets the global state for the singleton instance of the ssoDialog:
```typescript
  async run(parameters: any): Promise<any> {
    this.validateParameters(parameters);
    const ssoDialog = parameters.ssoDialog;
    ssoDialog.setSSOOperation(this.operationWithSSOToken);
    await ssoDialog.run(parameters.context, parameters.dialogState);
  }
```

And the next call of that method overwrites the global state of `ssoDialog`, which leads to the problem that after it's overwritten – any command which is currently waiting for user input (access grant) will execute the last set callback.

## Probable solution

I think every command which needs to use SSODialog should create a new instance, where the instance should always be immutable. And all of the data within that dialog should be stored within some storage (like `dedupStorage`, but probably with a higher level of abstraction, which will cover the `dedupStorageKeys`).

## Video how it was reproduced

https://user-images.githubusercontent.com/5353364/207709225-6f49c7f3-6f4b-4fe4-bde5-2de2e4a7a977.mp4

**Comment by yukun-dong** [comment]
Hi @ValeriyMaslenikov,

Thanks for bringing this issue to our attention. We apologize for the delayed response.

We would like to inform you that the "bot-sso" sample you have reported is going to be retired soon. However, we have another sample called "command-bot-with-sso" which offers similar functionality and resolves the issue you have reported. We encourage you to try out this sample for a better experience.

Thank you for your continued support and please let us know if you have any further concerns.

**Comment by yukun-dong** [comment]
Hi @ValeriyMaslenikov, 

We are closing this issue. Feel free to reopen or create a new issue if you still got related problems. Thanks for your support.
