### ISSUE TITLE
How long connections are stored in notification.localstore.json?

### ISSUE THREAD

**Issue by Steffi3rd** [OfficeDev/TeamsFx-Samples#840]
Hi! 

When I test the bot locally, I have no issues between bot and users. 
I mean: Users still receive notifications from the bot (So I guess because users are always present in notification.localstore.json)

However, in production, users do receive notifications from the bot when they install the application. But after a certain time (how long?), the bot no longer finds the users and can no longer send notifications messages to them.

For the bot to be able to send new notification messages to users, the user must "respond" to the bot. And then it works again.

So I have 3 questions:

- After how long are users no longer taken into account by the bot?
- Is there a way to maintain the connection between the bot and the user (for example, until the user uninstalls the application?)
- If not, is there a way to modify/increase the time before the connection between the bot and the user is deleted?

Here are the links I found about notification storage but not implemented it yet: 
-  Use Azure Blob Storage to persist notification connections : [notification.localstore.json](https://github.com/OfficeDev/TeamsFx-Samples/blob/1e1c86c6f294012438474bb2f806e307d607c47b/adaptive-card-notification/README.md#optional-use-azure-blob-storage-to-persist-notification-connections)
- Add notification storage implementation sample : (https://github.com/OfficeDev/TeamsFx-Samples/commit/99eb772226a6c0603b4ed52788e660773e865a64) https://github.com/OfficeDev/TeamsFx-Samples/blob/ga/adaptive-card-notification/bot/src/storage/blobsStorage.ts

Last question 
- If we implemented notification.localstore.json ourself, where we can found it Azure please? 

Thank you!

**Comment by qinezh** [comment]
Closed as duplicated with https://github.com/OfficeDev/TeamsFx/issues/8364
