### ISSUE TITLE
todo-list-SPFx fails with SharePoint 404

### ISSUE THREAD

**Issue by johnnydecimal** [OfficeDev/TeamsFx-Samples#934]
A basic provisioning of [todo-list-SPFx](https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/todo-list-SPFx) fails.

1. Create a new app using the Teams Toolkit.
2. Launch in Teams workbench (Edge).
3. Try to add to team.
4. `Error: [HTTP]:404 - [CorrelationId]:3dbdc3a0-c01f-3000-e624-66166ba602ef [Version]:16.0.0.23821`

It looks like the request to `https://z58q4.sharepoint.com/sites/Johnny.Decimal/_api/web/hostedapps/add` is causing the error. Visiting that page returns:

```xml
<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
  <m:code>-1, Microsoft.SharePoint.Client.ResourceNotFoundException</m:code>
  <m:message xml:lang="en-US">Cannot find resource for the request SP.RequestContext.current/web/hostedapps/.</m:message>
</m:error>
```

**Comment by HuihuiWu-Microsoft** [comment]
Hi @johnnydecimal, thanks for reporting this to us! I'd like to confirm with you whether you're using vanity domain account for Teams since it's a known issue that only non-vanity domain account is supported for Teams workbench for now.

**Comment by HuihuiWu-Microsoft** [comment]
@johnnydecimal I'll close this issue if you don't have more questions. Feel free to reopen if you still have problem with it.
