### ISSUE TITLE
`teamsfx` cli isn't downloading the latest versions

### ISSUE THREAD

**Issue by johnnydecimal** [OfficeDev/TeamsFx-Samples#935]
I hope I'm going mad because if not, this is terribly disappointing.

At the command line, the following command:

`teamsfx new template graph-connector-app`

downloads a repository that is _not_ the latest as per this repository.

The only file I've looked at is `README.md` but the version downloaded by `teamsfx` does not include [the note about single-tenant provisioning at line 7](https://github.com/OfficeDev/TeamsFx-Samples/blob/fbc9c68887dfe1289f4aef64a0a09181ae7921c2/graph-connector-app/README.md?plain=1#L7) that was committed 3 weeks ago. I'm not going to go back and figure out which version it _is_ downloading, assuming it even pulls from this repo.

This is maddening! All this time I've been trying to get stuff working and the tool isn't pulling the latest versions?! Tell me I'm wrong, please. I really want to be wrong.

**Comment by formulahendry** [comment]
@johnnydecimal CLI will download from the latest tag (https://github.com/OfficeDev/TeamsFx-Samples/tree/v2.3.0) not from the dev branch.
But the changes you mentioned are included in latest tag. So closing this issue.

Feel free to reopen or create a new issue if you still have problems.
